//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.ws {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TLogin", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class TLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTLogin {
            get {
                return this.IdTLoginField;
            }
            set {
                if ((this.IdTLoginField.Equals(value) != true)) {
                    this.IdTLoginField = value;
                    this.RaisePropertyChanged("IdTLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ws.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroTargetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ws.Pago PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ws.Polo PoloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ws.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroTargeta {
            get {
                return this.NroTargetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NroTargetaField, value) != true)) {
                    this.NroTargetaField = value;
                    this.RaisePropertyChanged("NroTargeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ws.Pago Pago {
            get {
                return this.PagoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagoField, value) != true)) {
                    this.PagoField = value;
                    this.RaisePropertyChanged("Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ws.Polo Polo {
            get {
                return this.PoloField;
            }
            set {
                if ((object.ReferenceEquals(this.PoloField, value) != true)) {
                    this.PoloField = value;
                    this.RaisePropertyChanged("Polo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ws.TLogin IdTLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroTargetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ws.TLogin IdTLogin {
            get {
                return this.IdTLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTLoginField, value) != true)) {
                    this.IdTLoginField = value;
                    this.RaisePropertyChanged("IdTLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroTargeta {
            get {
                return this.NroTargetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NroTargetaField, value) != true)) {
                    this.NroTargetaField = value;
                    this.RaisePropertyChanged("NroTargeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPago {
            get {
                return this.IdPagoField;
            }
            set {
                if ((this.IdPagoField.Equals(value) != true)) {
                    this.IdPagoField = value;
                    this.RaisePropertyChanged("IdPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Polo", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class Polo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ws.Color ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ws.Design DesignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TallaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ws.Color Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ws.Design Design {
            get {
                return this.DesignField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignField, value) != true)) {
                    this.DesignField = value;
                    this.RaisePropertyChanged("Design");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPolo {
            get {
                return this.IdPoloField;
            }
            set {
                if ((this.IdPoloField.Equals(value) != true)) {
                    this.IdPoloField = value;
                    this.RaisePropertyChanged("IdPolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Talla {
            get {
                return this.TallaField;
            }
            set {
                if ((object.ReferenceEquals(this.TallaField, value) != true)) {
                    this.TallaField = value;
                    this.RaisePropertyChanged("Talla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class Color : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColor {
            get {
                return this.IdColorField;
            }
            set {
                if ((this.IdColorField.Equals(value) != true)) {
                    this.IdColorField = value;
                    this.RaisePropertyChanged("IdColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Design", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class Design : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDesignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDesign {
            get {
                return this.IdDesignField;
            }
            set {
                if ((this.IdDesignField.Equals(value) != true)) {
                    this.IdDesignField = value;
                    this.RaisePropertyChanged("IdDesign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePedido", Namespace="http://schemas.datacontract.org/2004/07/DoDesign.Service.Dominio")]
    [System.SerializableAttribute()]
    public partial class DetallePedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDetallePedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ws.Pedido PedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDetallePedido {
            get {
                return this.IdDetallePedidoField;
            }
            set {
                if ((this.IdDetallePedidoField.Equals(value) != true)) {
                    this.IdDetallePedidoField = value;
                    this.RaisePropertyChanged("IdDetallePedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ws.Pedido Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws.ITransaccion")]
    public interface ITransaccion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/LoginCliente", ReplyAction="http://tempuri.org/ITransaccion/LoginClienteResponse")]
        bool LoginCliente(UnitTestProject1.ws.TLogin logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/LoginCliente", ReplyAction="http://tempuri.org/ITransaccion/LoginClienteResponse")]
        System.Threading.Tasks.Task<bool> LoginClienteAsync(UnitTestProject1.ws.TLogin logueo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearPedido", ReplyAction="http://tempuri.org/ITransaccion/CrearPedidoResponse")]
        UnitTestProject1.ws.Pedido CrearPedido(UnitTestProject1.ws.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearPedido", ReplyAction="http://tempuri.org/ITransaccion/CrearPedidoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Pedido> CrearPedidoAsync(UnitTestProject1.ws.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarPedido", ReplyAction="http://tempuri.org/ITransaccion/ListarPedidoResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.Pedido> ListarPedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarPedido", ReplyAction="http://tempuri.org/ITransaccion/ListarPedidoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Pedido>> ListarPedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarPedido", ReplyAction="http://tempuri.org/ITransaccion/ModificarPedidoResponse")]
        UnitTestProject1.ws.Pedido ModificarPedido(UnitTestProject1.ws.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarPedido", ReplyAction="http://tempuri.org/ITransaccion/ModificarPedidoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Pedido> ModificarPedidoAsync(UnitTestProject1.ws.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerPedido", ReplyAction="http://tempuri.org/ITransaccion/ObtenerPedidoResponse")]
        UnitTestProject1.ws.Pedido ObtenerPedido(int IdPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerPedido", ReplyAction="http://tempuri.org/ITransaccion/ObtenerPedidoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Pedido> ObtenerPedidoAsync(int IdPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearCliente", ReplyAction="http://tempuri.org/ITransaccion/CrearClienteResponse")]
        UnitTestProject1.ws.Cliente CrearCliente(UnitTestProject1.ws.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearCliente", ReplyAction="http://tempuri.org/ITransaccion/CrearClienteResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Cliente> CrearClienteAsync(UnitTestProject1.ws.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarCliente", ReplyAction="http://tempuri.org/ITransaccion/ListarClienteResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.Cliente> ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarCliente", ReplyAction="http://tempuri.org/ITransaccion/ListarClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Cliente>> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarCliente", ReplyAction="http://tempuri.org/ITransaccion/ModificarClienteResponse")]
        UnitTestProject1.ws.Cliente ModificarCliente(UnitTestProject1.ws.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarCliente", ReplyAction="http://tempuri.org/ITransaccion/ModificarClienteResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Cliente> ModificarClienteAsync(UnitTestProject1.ws.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCliente", ReplyAction="http://tempuri.org/ITransaccion/ObtenerClienteResponse")]
        UnitTestProject1.ws.Cliente ObtenerCliente(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCliente", ReplyAction="http://tempuri.org/ITransaccion/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Cliente> ObtenerClienteAsync(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearColor", ReplyAction="http://tempuri.org/ITransaccion/CrearColorResponse")]
        UnitTestProject1.ws.Color CrearColor(UnitTestProject1.ws.Color color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearColor", ReplyAction="http://tempuri.org/ITransaccion/CrearColorResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Color> CrearColorAsync(UnitTestProject1.ws.Color color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarColor", ReplyAction="http://tempuri.org/ITransaccion/ListarColorResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.Color> ListarColor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarColor", ReplyAction="http://tempuri.org/ITransaccion/ListarColorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Color>> ListarColorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarColor", ReplyAction="http://tempuri.org/ITransaccion/ModificarColorResponse")]
        UnitTestProject1.ws.Color ModificarColor(UnitTestProject1.ws.Color color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarColor", ReplyAction="http://tempuri.org/ITransaccion/ModificarColorResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Color> ModificarColorAsync(UnitTestProject1.ws.Color color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerColor", ReplyAction="http://tempuri.org/ITransaccion/ObtenerColorResponse")]
        UnitTestProject1.ws.Color ObtenerColor(int IdColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerColor", ReplyAction="http://tempuri.org/ITransaccion/ObtenerColorResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Color> ObtenerColorAsync(int IdColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearDesign", ReplyAction="http://tempuri.org/ITransaccion/CrearDesignResponse")]
        UnitTestProject1.ws.Design CrearDesign(UnitTestProject1.ws.Design design);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearDesign", ReplyAction="http://tempuri.org/ITransaccion/CrearDesignResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Design> CrearDesignAsync(UnitTestProject1.ws.Design design);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarDesign", ReplyAction="http://tempuri.org/ITransaccion/ListarDesignResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.Design> ListarDesign();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarDesign", ReplyAction="http://tempuri.org/ITransaccion/ListarDesignResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Design>> ListarDesignAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarDesign", ReplyAction="http://tempuri.org/ITransaccion/ModificarDesignResponse")]
        UnitTestProject1.ws.Design ModificarDesign(UnitTestProject1.ws.Design design);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarDesign", ReplyAction="http://tempuri.org/ITransaccion/ModificarDesignResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Design> ModificarDesignAsync(UnitTestProject1.ws.Design design);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerDesign", ReplyAction="http://tempuri.org/ITransaccion/ObtenerDesignResponse")]
        UnitTestProject1.ws.Design ObtenerDesign(int IdDesign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerDesign", ReplyAction="http://tempuri.org/ITransaccion/ObtenerDesignResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Design> ObtenerDesignAsync(int IdDesign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/CrearDetallePedidoResponse")]
        UnitTestProject1.ws.DetallePedido CrearDetallePedido(UnitTestProject1.ws.DetallePedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/CrearDetallePedidoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.DetallePedido> CrearDetallePedidoAsync(UnitTestProject1.ws.DetallePedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/ListarDetallePedidoResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.DetallePedido> ListarDetallePedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/ListarDetallePedidoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.DetallePedido>> ListarDetallePedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/ModificarDetallePedidoResponse")]
        UnitTestProject1.ws.DetallePedido ModificarDetallePedido(UnitTestProject1.ws.DetallePedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/ModificarDetallePedidoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.DetallePedido> ModificarDetallePedidoAsync(UnitTestProject1.ws.DetallePedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/ObtenerDetallePedidoResponse")]
        UnitTestProject1.ws.DetallePedido ObtenerDetallePedido(int IdDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerDetallePedido", ReplyAction="http://tempuri.org/ITransaccion/ObtenerDetallePedidoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.DetallePedido> ObtenerDetallePedidoAsync(int IdDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearPago", ReplyAction="http://tempuri.org/ITransaccion/CrearPagoResponse")]
        UnitTestProject1.ws.Pago CrearPago(UnitTestProject1.ws.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearPago", ReplyAction="http://tempuri.org/ITransaccion/CrearPagoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Pago> CrearPagoAsync(UnitTestProject1.ws.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarPago", ReplyAction="http://tempuri.org/ITransaccion/ListarPagoResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.Pago> ListarPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarPago", ReplyAction="http://tempuri.org/ITransaccion/ListarPagoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Pago>> ListarPagoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarPago", ReplyAction="http://tempuri.org/ITransaccion/ModificarPagoResponse")]
        UnitTestProject1.ws.Pago ModificarPago(UnitTestProject1.ws.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarPago", ReplyAction="http://tempuri.org/ITransaccion/ModificarPagoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Pago> ModificarPagoAsync(UnitTestProject1.ws.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerPago", ReplyAction="http://tempuri.org/ITransaccion/ObtenerPagoResponse")]
        UnitTestProject1.ws.Pago ObtenerPago(int IdPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerPago", ReplyAction="http://tempuri.org/ITransaccion/ObtenerPagoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Pago> ObtenerPagoAsync(int IdPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearPolo", ReplyAction="http://tempuri.org/ITransaccion/CrearPoloResponse")]
        UnitTestProject1.ws.Polo CrearPolo(UnitTestProject1.ws.Polo polo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearPolo", ReplyAction="http://tempuri.org/ITransaccion/CrearPoloResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Polo> CrearPoloAsync(UnitTestProject1.ws.Polo polo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarPolo", ReplyAction="http://tempuri.org/ITransaccion/ListarPoloResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.Polo> ListarPolo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarPolo", ReplyAction="http://tempuri.org/ITransaccion/ListarPoloResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Polo>> ListarPoloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarPolo", ReplyAction="http://tempuri.org/ITransaccion/ModificarPoloResponse")]
        UnitTestProject1.ws.Polo ModificarPolo(UnitTestProject1.ws.Polo polo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarPolo", ReplyAction="http://tempuri.org/ITransaccion/ModificarPoloResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Polo> ModificarPoloAsync(UnitTestProject1.ws.Polo polo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerPolo", ReplyAction="http://tempuri.org/ITransaccion/ObtenerPoloResponse")]
        UnitTestProject1.ws.Polo ObtenerPolo(int IdPolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerPolo", ReplyAction="http://tempuri.org/ITransaccion/ObtenerPoloResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.Polo> ObtenerPoloAsync(int IdPolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearTLogin", ReplyAction="http://tempuri.org/ITransaccion/CrearTLoginResponse")]
        UnitTestProject1.ws.TLogin CrearTLogin(UnitTestProject1.ws.TLogin tlogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/CrearTLogin", ReplyAction="http://tempuri.org/ITransaccion/CrearTLoginResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.TLogin> CrearTLoginAsync(UnitTestProject1.ws.TLogin tlogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTLogin", ReplyAction="http://tempuri.org/ITransaccion/ListarTLoginResponse")]
        System.Collections.Generic.List<UnitTestProject1.ws.TLogin> ListarTLogin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTLogin", ReplyAction="http://tempuri.org/ITransaccion/ListarTLoginResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.TLogin>> ListarTLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarTlogin", ReplyAction="http://tempuri.org/ITransaccion/ModificarTloginResponse")]
        UnitTestProject1.ws.TLogin ModificarTlogin(UnitTestProject1.ws.TLogin tlogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ModificarTlogin", ReplyAction="http://tempuri.org/ITransaccion/ModificarTloginResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.TLogin> ModificarTloginAsync(UnitTestProject1.ws.TLogin tlogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTLogin", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTLoginResponse")]
        UnitTestProject1.ws.TLogin ObtenerTLogin(int IdTLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTLogin", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTLoginResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ws.TLogin> ObtenerTLoginAsync(int IdTLogin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransaccionChannel : UnitTestProject1.ws.ITransaccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransaccionClient : System.ServiceModel.ClientBase<UnitTestProject1.ws.ITransaccion>, UnitTestProject1.ws.ITransaccion {
        
        public TransaccionClient() {
        }
        
        public TransaccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransaccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LoginCliente(UnitTestProject1.ws.TLogin logueo) {
            return base.Channel.LoginCliente(logueo);
        }
        
        public System.Threading.Tasks.Task<bool> LoginClienteAsync(UnitTestProject1.ws.TLogin logueo) {
            return base.Channel.LoginClienteAsync(logueo);
        }
        
        public UnitTestProject1.ws.Pedido CrearPedido(UnitTestProject1.ws.Pedido pedido) {
            return base.Channel.CrearPedido(pedido);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Pedido> CrearPedidoAsync(UnitTestProject1.ws.Pedido pedido) {
            return base.Channel.CrearPedidoAsync(pedido);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.Pedido> ListarPedido() {
            return base.Channel.ListarPedido();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Pedido>> ListarPedidoAsync() {
            return base.Channel.ListarPedidoAsync();
        }
        
        public UnitTestProject1.ws.Pedido ModificarPedido(UnitTestProject1.ws.Pedido pedido) {
            return base.Channel.ModificarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Pedido> ModificarPedidoAsync(UnitTestProject1.ws.Pedido pedido) {
            return base.Channel.ModificarPedidoAsync(pedido);
        }
        
        public UnitTestProject1.ws.Pedido ObtenerPedido(int IdPedido) {
            return base.Channel.ObtenerPedido(IdPedido);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Pedido> ObtenerPedidoAsync(int IdPedido) {
            return base.Channel.ObtenerPedidoAsync(IdPedido);
        }
        
        public UnitTestProject1.ws.Cliente CrearCliente(UnitTestProject1.ws.Cliente cliente) {
            return base.Channel.CrearCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Cliente> CrearClienteAsync(UnitTestProject1.ws.Cliente cliente) {
            return base.Channel.CrearClienteAsync(cliente);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.Cliente> ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Cliente>> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
        
        public UnitTestProject1.ws.Cliente ModificarCliente(UnitTestProject1.ws.Cliente cliente) {
            return base.Channel.ModificarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Cliente> ModificarClienteAsync(UnitTestProject1.ws.Cliente cliente) {
            return base.Channel.ModificarClienteAsync(cliente);
        }
        
        public UnitTestProject1.ws.Cliente ObtenerCliente(int IdCliente) {
            return base.Channel.ObtenerCliente(IdCliente);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Cliente> ObtenerClienteAsync(int IdCliente) {
            return base.Channel.ObtenerClienteAsync(IdCliente);
        }
        
        public UnitTestProject1.ws.Color CrearColor(UnitTestProject1.ws.Color color) {
            return base.Channel.CrearColor(color);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Color> CrearColorAsync(UnitTestProject1.ws.Color color) {
            return base.Channel.CrearColorAsync(color);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.Color> ListarColor() {
            return base.Channel.ListarColor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Color>> ListarColorAsync() {
            return base.Channel.ListarColorAsync();
        }
        
        public UnitTestProject1.ws.Color ModificarColor(UnitTestProject1.ws.Color color) {
            return base.Channel.ModificarColor(color);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Color> ModificarColorAsync(UnitTestProject1.ws.Color color) {
            return base.Channel.ModificarColorAsync(color);
        }
        
        public UnitTestProject1.ws.Color ObtenerColor(int IdColor) {
            return base.Channel.ObtenerColor(IdColor);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Color> ObtenerColorAsync(int IdColor) {
            return base.Channel.ObtenerColorAsync(IdColor);
        }
        
        public UnitTestProject1.ws.Design CrearDesign(UnitTestProject1.ws.Design design) {
            return base.Channel.CrearDesign(design);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Design> CrearDesignAsync(UnitTestProject1.ws.Design design) {
            return base.Channel.CrearDesignAsync(design);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.Design> ListarDesign() {
            return base.Channel.ListarDesign();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Design>> ListarDesignAsync() {
            return base.Channel.ListarDesignAsync();
        }
        
        public UnitTestProject1.ws.Design ModificarDesign(UnitTestProject1.ws.Design design) {
            return base.Channel.ModificarDesign(design);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Design> ModificarDesignAsync(UnitTestProject1.ws.Design design) {
            return base.Channel.ModificarDesignAsync(design);
        }
        
        public UnitTestProject1.ws.Design ObtenerDesign(int IdDesign) {
            return base.Channel.ObtenerDesign(IdDesign);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Design> ObtenerDesignAsync(int IdDesign) {
            return base.Channel.ObtenerDesignAsync(IdDesign);
        }
        
        public UnitTestProject1.ws.DetallePedido CrearDetallePedido(UnitTestProject1.ws.DetallePedido detallePedido) {
            return base.Channel.CrearDetallePedido(detallePedido);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.DetallePedido> CrearDetallePedidoAsync(UnitTestProject1.ws.DetallePedido detallePedido) {
            return base.Channel.CrearDetallePedidoAsync(detallePedido);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.DetallePedido> ListarDetallePedido() {
            return base.Channel.ListarDetallePedido();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.DetallePedido>> ListarDetallePedidoAsync() {
            return base.Channel.ListarDetallePedidoAsync();
        }
        
        public UnitTestProject1.ws.DetallePedido ModificarDetallePedido(UnitTestProject1.ws.DetallePedido detallePedido) {
            return base.Channel.ModificarDetallePedido(detallePedido);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.DetallePedido> ModificarDetallePedidoAsync(UnitTestProject1.ws.DetallePedido detallePedido) {
            return base.Channel.ModificarDetallePedidoAsync(detallePedido);
        }
        
        public UnitTestProject1.ws.DetallePedido ObtenerDetallePedido(int IdDetallePedido) {
            return base.Channel.ObtenerDetallePedido(IdDetallePedido);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.DetallePedido> ObtenerDetallePedidoAsync(int IdDetallePedido) {
            return base.Channel.ObtenerDetallePedidoAsync(IdDetallePedido);
        }
        
        public UnitTestProject1.ws.Pago CrearPago(UnitTestProject1.ws.Pago pago) {
            return base.Channel.CrearPago(pago);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Pago> CrearPagoAsync(UnitTestProject1.ws.Pago pago) {
            return base.Channel.CrearPagoAsync(pago);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.Pago> ListarPago() {
            return base.Channel.ListarPago();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Pago>> ListarPagoAsync() {
            return base.Channel.ListarPagoAsync();
        }
        
        public UnitTestProject1.ws.Pago ModificarPago(UnitTestProject1.ws.Pago pago) {
            return base.Channel.ModificarPago(pago);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Pago> ModificarPagoAsync(UnitTestProject1.ws.Pago pago) {
            return base.Channel.ModificarPagoAsync(pago);
        }
        
        public UnitTestProject1.ws.Pago ObtenerPago(int IdPago) {
            return base.Channel.ObtenerPago(IdPago);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Pago> ObtenerPagoAsync(int IdPago) {
            return base.Channel.ObtenerPagoAsync(IdPago);
        }
        
        public UnitTestProject1.ws.Polo CrearPolo(UnitTestProject1.ws.Polo polo) {
            return base.Channel.CrearPolo(polo);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Polo> CrearPoloAsync(UnitTestProject1.ws.Polo polo) {
            return base.Channel.CrearPoloAsync(polo);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.Polo> ListarPolo() {
            return base.Channel.ListarPolo();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.Polo>> ListarPoloAsync() {
            return base.Channel.ListarPoloAsync();
        }
        
        public UnitTestProject1.ws.Polo ModificarPolo(UnitTestProject1.ws.Polo polo) {
            return base.Channel.ModificarPolo(polo);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Polo> ModificarPoloAsync(UnitTestProject1.ws.Polo polo) {
            return base.Channel.ModificarPoloAsync(polo);
        }
        
        public UnitTestProject1.ws.Polo ObtenerPolo(int IdPolo) {
            return base.Channel.ObtenerPolo(IdPolo);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.Polo> ObtenerPoloAsync(int IdPolo) {
            return base.Channel.ObtenerPoloAsync(IdPolo);
        }
        
        public UnitTestProject1.ws.TLogin CrearTLogin(UnitTestProject1.ws.TLogin tlogin) {
            return base.Channel.CrearTLogin(tlogin);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.TLogin> CrearTLoginAsync(UnitTestProject1.ws.TLogin tlogin) {
            return base.Channel.CrearTLoginAsync(tlogin);
        }
        
        public System.Collections.Generic.List<UnitTestProject1.ws.TLogin> ListarTLogin() {
            return base.Channel.ListarTLogin();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UnitTestProject1.ws.TLogin>> ListarTLoginAsync() {
            return base.Channel.ListarTLoginAsync();
        }
        
        public UnitTestProject1.ws.TLogin ModificarTlogin(UnitTestProject1.ws.TLogin tlogin) {
            return base.Channel.ModificarTlogin(tlogin);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.TLogin> ModificarTloginAsync(UnitTestProject1.ws.TLogin tlogin) {
            return base.Channel.ModificarTloginAsync(tlogin);
        }
        
        public UnitTestProject1.ws.TLogin ObtenerTLogin(int IdTLogin) {
            return base.Channel.ObtenerTLogin(IdTLogin);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ws.TLogin> ObtenerTLoginAsync(int IdTLogin) {
            return base.Channel.ObtenerTLoginAsync(IdTLogin);
        }
    }
}
